const KEY='susu-min-v1';
const foods=[
{name:'Khao Man Gai',kcal:650,p:38,c:78,f:20},{name:'Pad Kra Pao + huevo',kcal:720,p:35,c:78,f:28},{name:'Gai Yang + arroz',kcal:590,p:52,c:65,f:13},{name:'Pechuga de pollo 7-Eleven',kcal:120,p:23,c:4,f:2},{name:'4 huevos',kcal:288,p:25,c:2,f:20},{name:'Protein shake',kcal:130,p:25,c:4,f:2},{name:'Arroz jazmín 200 g',kcal:260,p:5,c:57,f:1},{name:'Atún al natural',kcal:130,p:29,c:0,f:1},{name:'Yogur griego',kcal:150,p:15,c:10,f:5},{name:'Som Tam',kcal:160,p:4,c:28,f:4}];
const iso=d=>{const x=new Date(d-Date.now()%1);return x.toLocaleDateString('en-CA')};
const today=()=>new Date().toLocaleDateString('en-CA');
const defaults={profile:{pushGoal:100,kcalGoal:2300,proteinGoal:165,carbGoal:250,fatGoal:70,geminiEndpoint:''},days:{},measurements:[],photos:[]};
let s=load(),view='today',period=30;
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x?Object.assign(structuredClone(defaults),x):structuredClone(defaults)}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(s))}
function day(k=today()){return s.days[k]||(s.days[k]={pushups:0,pullups:0,meals:[]})}
function n(v){return Number(v)||0}
function dayTotals(d=day()){return d.meals.reduce((a,m)=>({kcal:a.kcal+n(m.kcal),p:a.p+n(m.p),c:a.c+n(m.c),f:a.f+n(m.f)}),{kcal:0,p:0,c:0,f:0})}
function monthDays(){const t=new Date(), y=t.getFullYear(),m=t.getMonth(),out=[];for(let i=1;i<=t.getDate();i++){const d=new Date(y,m,i);out.push(d.toLocaleDateString('en-CA'))}return out}
function pushAvg(){const ds=monthDays();return Math.round(ds.reduce((a,k)=>a+n(s.days[k]?.pushups),0)/Math.max(1,ds.length))}
function esc(x=''){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function layout(body){return `<div class="app"><div class="top"><div class="logo">SU SU</div><button class="iconbtn" data-act="settings">⚙︎</button></div>${body}</div><nav class="nav"><button data-view="today" class="${view==='today'?'active':''}">Hoy</button><button data-view="progress" class="${view==='progress'?'active':''}">Progreso</button></nav><div class="modal" id="modal"><div class="sheet"><div class="handle"></div><div id="sheet"></div></div></div>`}
function todayView(){const d=day(),t=dayTotals(d),avg=pushAvg(),goal=s.profile.pushGoal,good=avg>=goal;return layout(`<section class="hero"><div class="number">${avg}</div><div class="label">FLEXIONES / DÍA</div><div class="goal">Objetivo ${goal}</div><div class="message ${good?'good':'bad'}">${good?'Vamos papuuuuuu 🔥':'¿Eres un ladyboy?'}</div><div class="stepper"><button class="pillbtn" data-push="-10">− 10</button><button class="pillbtn" data-push="10">+ 10</button><button class="pillbtn" data-push="25">+ 25</button></div></section><div class="divider"></div><section class="kcal"><div class="number">${Math.round(t.kcal).toLocaleString()}</div><div class="label">KCAL</div><div class="remaining">${Math.max(0,s.profile.kcalGoal-t.kcal).toLocaleString()} kcal restantes</div><div class="actions"><button class="action" data-act="food"><span class="tinyaccent"></span> Buscar</button><button class="action camera" data-act="camera">⌁ Foto</button></div><div class="macroline"><span>P ${Math.round(t.p)}/${s.profile.proteinGoal}g</span><span>C ${Math.round(t.c)}/${s.profile.carbGoal}g</span><span>G ${Math.round(t.f)}/${s.profile.fatGoal}g</span></div></section><div class="divider"></div><section class="summary"><div class="sectionhead"><h2>HOY</h2><span>${new Date().toLocaleDateString('es',{day:'numeric',month:'short'})}</span></div><div class="twocol"><div class="stat"><strong>${d.pushups}</strong><span>flexiones</span></div><div class="stat"><strong>${d.pullups}</strong><span>dominadas · <button class="del" data-act="pull">+</button></span></div></div>${d.meals.length?`<div class="meal-list">${d.meals.map(m=>`<div class="meal"><div><b>${esc(m.name)}</b><small>${Math.round(m.kcal)} kcal · ${Math.round(m.p)}g proteína</small></div><button class="del" data-delmeal="${m.id}">×</button></div>`).join('')}</div>`:''}</section>`)}
function series(type,daysCount){let out=[];for(let i=daysCount-1;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);let k=d.toLocaleDateString('en-CA');let v=0;if(type==='push')v=n(s.days[k]?.pushups);if(type==='pull')v=n(s.days[k]?.pullups);if(type==='weight'){let x=[...s.measurements].reverse().find(m=>m.date<=k&&m.weight);v=n(x?.weight)}if(type==='waist'){let x=[...s.measurements].reverse().find(m=>m.date<=k&&m.waist);v=n(x?.waist)}out.push({k,v})}return out}
function chart(data){const vals=data.map(x=>x.v).filter(Boolean),min=vals.length?Math.min(...vals):0,max=vals.length?Math.max(...vals):1,span=Math.max(1,max-min),pts=data.map((x,i)=>`${i/(data.length-1||1)*100},${155-(x.v-min)/span*125}`).join(' ');return `<svg class="chart" viewBox="0 0 100 180" preserveAspectRatio="none"><line x1="0" y1="155" x2="100" y2="155" stroke="#eee"/><polyline points="${pts}" fill="none" stroke="#111" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round"/></svg>`}
function progressView(){const avg=pushAvg(),all=Object.values(s.days),prPush=Math.max(0,...all.map(d=>n(d.pushups))),prPull=Math.max(0,...all.map(d=>n(d.pullups))),last=s.measurements.at(-1)||{},prev=s.measurements.at(-2)||{};return layout(`<section class="progressHero"><div class="number">${avg}</div><div class="label">FLEXIONES / DÍA ESTE MES</div></section><div class="tabs"><button class="${period===7?'active':''}" data-period="7">7D</button><button class="${period===30?'active':''}" data-period="30">30D</button><button class="${period===90?'active':''}" data-period="90">3M</button><button class="${period===365?'active':''}" data-period="365">1A</button></div>${chart(series('push',period))}<div class="sectionhead"><h2>FUERZA</h2><span>récord diario</span></div><div class="cards"><div class="card"><span>Flexiones</span><strong>${prPush}</strong></div><div class="card"><span>Dominadas</span><strong>${prPull}</strong></div></div><div class="sectionhead" style="margin-top:32px"><h2>CUERPO</h2><span>check-in semanal</span></div><div class="row"><div><b>Peso</b><div class="goal">${last.weight?last.weight+' kg':'Sin datos'} ${last.weight&&prev.weight?`· ${last.weight-prev.weight>0?'+':''}${(last.weight-prev.weight).toFixed(1)}`:''}</div></div><button data-act="checkin">Añadir</button></div><div class="row"><div><b>Cintura</b><div class="goal">${last.waist?last.waist+' cm':'Sin datos'}</div></div><button data-act="checkin">Añadir</button></div><div class="sectionhead" style="margin-top:28px"><h2>FOTOS</h2><span>${s.photos.length} guardadas</span></div>${s.photos.length?`<div class="photos">${s.photos.slice(-4).reverse().map(p=>`<div class="photo"><img src="${p.data}"><small>${p.date}</small></div>`).join('')}</div><button class="secondary" data-act="compare">Comparar progreso</button>`:'<div class="empty">Haz una foto semanal con luz y posición parecidas para comparar de verdad.</div>'}<button class="primary" data-act="progressPhoto">＋ Foto de progreso</button>`) }
function render(){document.querySelector('#app').innerHTML=view==='today'?todayView():progressView();bind()}
function modal(html){document.querySelector('#sheet').innerHTML=html;document.querySelector('#modal').classList.add('show')}
function close(){document.querySelector('#modal').classList.remove('show')}
function foodModal(){modal(`<h2>Añadir comida</h2><input class="input" id="foodSearch" placeholder="Buscar comida…" autofocus><div class="searchResults" id="foodResults"></div><button class="secondary" data-act="manual">＋ Crear manualmente</button><p class="note">Los valores de platos preparados son estimaciones editables.</p>`);foodResults('')}
function foodResults(q){const r=foods.filter(f=>f.name.toLowerCase().includes(q.toLowerCase())).slice(0,8);document.querySelector('#foodResults').innerHTML=r.map((f,i)=>`<button data-food="${foods.indexOf(f)}"><b>${f.name}</b><small>${f.kcal} kcal · ${f.p}g proteína · ${f.c}g carb · ${f.f}g grasa</small></button>`).join('');bindSheet()}
function manualForm(pref={}){modal(`<h2>${pref.ai?'Revisar estimación':'Comida manual'}</h2>${pref.image?`<img class="aiPreview" src="${pref.image}">`:''}<form id="mealForm"><input class="input" name="name" placeholder="Comida" value="${esc(pref.name||'')}" required><div class="formgrid"><input class="input" name="kcal" type="number" step="1" placeholder="kcal" value="${pref.kcal??''}" required><input class="input" name="p" type="number" step=".1" placeholder="Proteína g" value="${pref.p??''}"><input class="input" name="c" type="number" step=".1" placeholder="Carbos g" value="${pref.c??''}"><input class="input" name="f" type="number" step=".1" placeholder="Grasa g" value="${pref.f??''}"></div>${pref.ai?'<p class="note">Estimación por imagen. Corrige cantidades si hace falta antes de guardar.</p>':''}<button class="primary">Guardar</button></form>`);document.querySelector('#mealForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);addMeal({name:f.get('name'),kcal:n(f.get('kcal')),p:n(f.get('p')),c:n(f.get('c')),f:n(f.get('f'))});close();render()}}
function addMeal(m){day().meals.push({...m,id:crypto.randomUUID?.()||Date.now()});save()}
function settings(){modal(`<h2>Ajustes</h2><form id="settingsForm" class="settings"><label>Objetivo media flexiones / día</label><input class="input" name="pushGoal" type="number" value="${s.profile.pushGoal}"><label>Objetivo kcal</label><input class="input" name="kcalGoal" type="number" value="${s.profile.kcalGoal}"><label>Proteína / día (g)</label><input class="input" name="proteinGoal" type="number" value="${s.profile.proteinGoal}"><label>Carbohidratos / día (g)</label><input class="input" name="carbGoal" type="number" value="${s.profile.carbGoal}"><label>Grasas / día (g)</label><input class="input" name="fatGoal" type="number" value="${s.profile.fatGoal}"><label>Endpoint privado para Gemini (opcional)</label><input class="input" name="geminiEndpoint" value="${esc(s.profile.geminiEndpoint||'')}" placeholder="https://…/analyze-meal"><p class="note">No pongas una API key de Gemini aquí. GitHub Pages es público. Usa un endpoint privado (por ejemplo, un Worker) que guarde la clave como secreto.</p><button class="primary">Guardar</button></form><button class="secondary" data-act="export">Exportar backup</button><button class="secondary" data-act="import">Importar backup</button>`);document.querySelector('#settingsForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);['pushGoal','kcalGoal','proteinGoal','carbGoal','fatGoal'].forEach(k=>s.profile[k]=n(f.get(k)));s.profile.geminiEndpoint=f.get('geminiEndpoint').trim();save();close();render()}}
function checkin(){modal(`<h2>Weekly check-in</h2><form id="checkForm"><input class="input" name="weight" type="number" step=".1" placeholder="Peso (kg)"><input class="input" name="waist" type="number" step=".1" placeholder="Cintura (cm)"><input class="input" name="chest" type="number" step=".1" placeholder="Pecho (cm) · opcional"><input class="input" name="arm" type="number" step=".1" placeholder="Brazo (cm) · opcional"><button class="primary">Guardar</button></form>`);document.querySelector('#checkForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);s.measurements.push({date:today(),weight:n(f.get('weight'))||null,waist:n(f.get('waist'))||null,chest:n(f.get('chest'))||null,arm:n(f.get('arm'))||null});save();close();render()}}
async function compress(file,max=1000,q=.76){const img=await createImageBitmap(file),scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);return c.toDataURL('image/jpeg',q)}
async function analyzeMeal(data){if(!s.profile.geminiEndpoint){manualForm({image:data});return}modal(`<h2>Analizando comida…</h2><img class="aiPreview" src="${data}"><p class="note">Gemini está estimando plato, calorías y macros.</p>`);try{let r=await fetch(s.profile.geminiEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:data,prompt:'Estimate this meal. Return JSON only with name,kcal,protein_g,carbs_g,fat_g. Be conservative and practical.'})});if(!r.ok)throw Error('HTTP '+r.status);let x=await r.json();manualForm({image:data,ai:true,name:x.name,kcal:x.kcal,p:x.protein_g,c:x.carbs_g,f:x.fat_g})}catch(e){manualForm({image:data});alert('No se pudo analizar con Gemini. Puedes registrar la comida manualmente.') }}
function compare(){if(s.photos.length<2)return alert('Necesitas al menos 2 fotos.');let a=s.photos[0],b=s.photos.at(-1);modal(`<h2>Tu progreso</h2><div class="compare"><div class="photo"><img src="${a.data}"><small>${a.date}</small></div><div class="photo"><img src="${b.data}"><small>${b.date}</small></div></div><p class="note">Las fotos se guardan solo en este dispositivo y se incluyen en tu backup.</p>`)}
function exportData(){let blob=new Blob([JSON.stringify(s,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`susu-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href)}
function bindSheet(){document.querySelectorAll('[data-food]').forEach(b=>b.onclick=()=>{addMeal(foods[+b.dataset.food]);close();render()});let q=document.querySelector('#foodSearch');if(q)q.oninput=()=>foodResults(q.value)}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});document.querySelectorAll('[data-push]').forEach(b=>b.onclick=()=>{day().pushups=Math.max(0,day().pushups+n(b.dataset.push));save();render()});document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{period=+b.dataset.period;render()});document.querySelectorAll('[data-delmeal]').forEach(b=>b.onclick=()=>{day().meals=day().meals.filter(m=>m.id!==b.dataset.delmeal);save();render()});document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>action(b.dataset.act));let m=document.querySelector('#modal');if(m)m.onclick=e=>{if(e.target===m)close()};bindSheet()}
function action(a){if(a==='settings')settings();if(a==='food')foodModal();if(a==='manual')manualForm();if(a==='camera')document.querySelector('#mealCamera').click();if(a==='pull'){let x=prompt('¿Cuántas dominadas?');if(x){day().pullups+=Math.max(0,n(x));save();render()}}if(a==='checkin')checkin();if(a==='progressPhoto')document.querySelector('#progressCamera').click();if(a==='compare')compare();if(a==='export')exportData();if(a==='import')document.querySelector('#importFile').click()}
document.querySelector('#mealCamera').onchange=async e=>{if(e.target.files[0])analyzeMeal(await compress(e.target.files[0],900,.72));e.target.value=''};
document.querySelector('#progressCamera').onchange=async e=>{if(e.target.files[0]){s.photos.push({id:Date.now(),date:today(),data:await compress(e.target.files[0],900,.7)});save();view='progress';render()}e.target.value=''};
document.querySelector('#importFile').onchange=async e=>{try{s=Object.assign(structuredClone(defaults),JSON.parse(await e.target.files[0].text()));save();close();render()}catch{alert('Backup no válido')}e.target.value=''};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
const params=new URLSearchParams(location.search);if(params.get('action')==='food')setTimeout(foodModal,100);if(params.get('action')==='pushups')setTimeout(()=>{day().pushups+=10;save();render()},100);
render();
