const KEY='susu-v6';
const V5_KEY='susu-v5';
const OLD_KEY='susu-min-v1';
const foods=[
{name:'Khao Man Gai',kcal:650,p:38,c:78,f:20},{name:'Pad Kra Pao + huevo',kcal:720,p:35,c:78,f:28},{name:'Gai Yang + arroz',kcal:590,p:52,c:65,f:13},{name:'Pechuga de pollo 7-Eleven',kcal:120,p:23,c:4,f:2},{name:'4 huevos',kcal:288,p:25,c:2,f:20},{name:'Protein shake',kcal:130,p:25,c:4,f:2},{name:'Arroz jazmín 200 g',kcal:260,p:5,c:57,f:1},{name:'Atún al natural',kcal:130,p:29,c:0,f:1},{name:'Yogur griego',kcal:150,p:15,c:10,f:5},{name:'Som Tam',kcal:160,p:4,c:28,f:4}];
const defaults={version:5,profile:{pushGoal:100,kcalGoal:2300,proteinGoal:165,carbGoal:250,fatGoal:70,geminiEndpoint:''},days:{},checkins:[]};
let s=load(),view='today',period=30,metric='push';
const today=()=>new Date().toLocaleDateString('en-CA');
const n=v=>Number(v)||0;
const id=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const esc=(x='')=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fresh(){return JSON.parse(JSON.stringify(defaults))}
function migrate(old){const out=fresh();out.profile={...out.profile,...(old.profile||{})};out.checkins=(old.measurements||[]).map((m,i)=>({...m,id:`old-${i}`,photos:[]}));for(const [k,d] of Object.entries(old.days||{})){out.days[k]={pushEvents:n(d.pushups)?[{id:id(),amount:n(d.pushups),at:`${k}T12:00:00`}]:[],pullEvents:n(d.pullups)?[{id:id(),amount:n(d.pullups),at:`${k}T12:00:00`}]:[],meals:d.meals||[]};}return out}
function load(){try{const v=JSON.parse(localStorage.getItem(KEY));if(v)return {...fresh(),...v,profile:{...fresh().profile,...v.profile}};const v5=JSON.parse(localStorage.getItem(V5_KEY));if(v5){localStorage.setItem(KEY,JSON.stringify(v5));return {...fresh(),...v5,profile:{...fresh().profile,...v5.profile}}}const old=JSON.parse(localStorage.getItem(OLD_KEY));if(old){const m=migrate(old);localStorage.setItem(KEY,JSON.stringify(m));return m}}catch{}return fresh()}
function save(){localStorage.setItem(KEY,JSON.stringify(s))}
function day(k=today()){return s.days[k]||(s.days[k]={pushEvents:[],pullEvents:[],meals:[]})}
function exerciseTotal(type,k=today()){const d=s.days[k];return (d?.[type+'Events']||[]).reduce((a,e)=>a+Math.max(0,Math.round(Number(e.amount)||0)),0)}
function dayTotals(d=day()){return (d.meals||[]).reduce((a,m)=>({kcal:a.kcal+n(m.kcal),p:a.p+n(m.p),c:a.c+n(m.c),f:a.f+n(m.f)}),{kcal:0,p:0,c:0,f:0})}
function monthKeys(){const t=new Date(),out=[];for(let i=1;i<=t.getDate();i++)out.push(new Date(t.getFullYear(),t.getMonth(),i).toLocaleDateString('en-CA'));return out}
function pushAvg(){const ks=monthKeys();return Math.round(ks.reduce((a,k)=>a+(s.days[k]?.pushEvents||[]).reduce((x,e)=>x+n(e.amount),0),0)/Math.max(1,ks.length))}
function streak(){let count=0;for(let i=0;i<365;i++){const d=new Date();d.setDate(d.getDate()-i);const k=d.toLocaleDateString('en-CA');const total=(s.days[k]?.pushEvents||[]).reduce((a,e)=>a+n(e.amount),0);if(total>=s.profile.pushGoal)count++;else if(i>0||total>0)break;else break}return count}
function layout(body){return `<div class="app"><header class="top"><div class="logo">SU SU</div><button class="iconbtn" data-act="settings" aria-label="Ajustes">•••</button></header>${body}</div><nav class="nav"><button data-view="today" class="${view==='today'?'active':''}">Hoy</button><button data-view="progress" class="${view==='progress'?'active':''}">Progreso</button></nav><div class="modal" id="modal"><div class="sheet"><div class="handle"></div><div id="sheet"></div></div></div><div id="toast" class="toast"></div>`}
function todayView(){const d=day(),t=dayTotals(d),avg=pushAvg(),goal=s.profile.pushGoal,good=avg>=goal,push=exerciseTotal('push'),pull=exerciseTotal('pull'),remain=Math.max(0,s.profile.kcalGoal-t.kcal);return layout(`<section class="hero"><div class="number">${avg}</div><div class="label">FLEXIONES / DÍA</div><div class="goal">Objetivo ${goal} · ${streak()?`🔥 ${streak()} días`:new Date().toLocaleDateString('es',{month:'long'})}</div><div class="message ${good?'good':'bad'}">${good?'Vamos papuuuuuu':'¿Eres un ladyboy?'}</div><div class="stepper"><button class="pillbtn" data-ex="push" data-amount="10">+10</button><button class="pillbtn" data-ex="push" data-amount="25">+25</button><button class="pillbtn subtle" data-act="customPush">+</button></div><button class="undo ${d.pushEvents?.length?'':'hidden'}" data-act="undoPush">Deshacer última</button></section><div class="divider"></div><section class="kcal"><div class="number">${Math.round(t.kcal).toLocaleString()}</div><div class="label">KCAL</div><div class="remaining">${Math.round(remain).toLocaleString()} restantes</div><div class="actions"><button class="action" data-act="food">⌕&nbsp; Buscar</button><button class="action" data-act="camera">◉&nbsp; Cámara</button><button class="action" data-act="gallery">▧&nbsp; Galería</button></div><div class="macroline"><span>${Math.round(t.p)} / ${s.profile.proteinGoal} g proteína</span></div></section><div class="divider"></div><section class="summary"><div class="sectionhead"><h2>HOY</h2><span>${new Date().toLocaleDateString('es',{day:'numeric',month:'short'})}</span></div><div class="twocol"><button class="stat" data-act="customPush"><strong>${push}</strong><span>flexiones</span></button><button class="stat" data-act="customPull"><strong>${pull}</strong><span>dominadas</span></button></div>${d.pushEvents?.length?`<div class="eventlog"><span>Últimos registros</span><b>${d.pushEvents.slice(-4).map(e=>'+'+Math.round(n(e.amount))).join(' · ')}</b></div>`:''}${d.meals?.length?`<details class="meals"><summary>${d.meals.length} comida${d.meals.length===1?'':'s'} registrada${d.meals.length===1?'':'s'}</summary><div class="meal-list">${d.meals.map(m=>`<div class="meal"><div><b>${esc(m.name)}</b><small>${Math.round(m.kcal)} kcal · ${Math.round(m.p)}g proteína</small></div><button class="del" data-delmeal="${m.id}">×</button></div>`).join('')}</div></details>`:''}</section>`)}
function metricValue(type,k){if(type==='push')return (s.days[k]?.pushEvents||[]).reduce((a,e)=>a+n(e.amount),0);if(type==='pull')return (s.days[k]?.pullEvents||[]).reduce((a,e)=>a+n(e.amount),0);const c=[...s.checkins].reverse().find(x=>x.date<=k&&n(x[type]));return n(c?.[type])}
function series(type,count){let out=[];for(let i=count-1;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=d.toLocaleDateString('en-CA');out.push({k,v:metricValue(type,k)})}return out}
function chart(data){const vals=data.map(x=>x.v).filter(v=>v>0);if(!vals.length)return `<div class="chartEmpty">Todavía no hay suficientes datos.</div>`;const min=Math.min(...vals),max=Math.max(...vals),span=Math.max(1,max-min),pts=data.map((x,i)=>`${i/(data.length-1||1)*100},${155-(x.v-min)/span*125}`).join(' ');return `<svg class="chart" viewBox="0 0 100 180" preserveAspectRatio="none"><line x1="0" y1="155" x2="100" y2="155" stroke="#eee"/><polyline points="${pts}" fill="none" stroke="#111" stroke-width="2" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round"/></svg>`}
function progressView(){const avg=pushAvg(),all=Object.keys(s.days),prPush=Math.max(0,...all.map(k=>metricValue('push',k))),prPull=Math.max(0,...all.map(k=>metricValue('pull',k))),last=s.checkins.at(-1)||{},prev=s.checkins.at(-2)||{},photos=s.checkins.reduce((a,c)=>a+(c.photos?.length||0),0);return layout(`<section class="progressHero"><div class="number">${avg}</div><div class="label">FLEXIONES / DÍA ESTE MES</div></section><div class="metricTabs"><button data-metric="push" class="${metric==='push'?'active':''}">Flex.</button><button data-metric="pull" class="${metric==='pull'?'active':''}">Dom.</button><button data-metric="weight" class="${metric==='weight'?'active':''}">Peso</button><button data-metric="waist" class="${metric==='waist'?'active':''}">Cintura</button></div><div class="tabs"><button class="${period===7?'active':''}" data-period="7">7D</button><button class="${period===30?'active':''}" data-period="30">30D</button><button class="${period===90?'active':''}" data-period="90">3M</button><button class="${period===365?'active':''}" data-period="365">1A</button></div>${chart(series(metric,period))}<div class="sectionhead"><h2>FUERZA</h2><span>récord diario</span></div><div class="cards"><div class="card"><span>Flexiones</span><strong>${prPush}</strong></div><div class="card"><span>Dominadas</span><strong>${prPull}</strong></div></div><div class="sectionhead bodyhead"><h2>CUERPO</h2><span>semanal</span></div><div class="bodySummary"><div><span>Peso</span><strong>${last.weight?last.weight+' kg':'—'}</strong>${last.weight&&prev.weight?`<small>${last.weight-prev.weight>0?'+':''}${(last.weight-prev.weight).toFixed(1)} kg</small>`:''}</div><div><span>Cintura</span><strong>${last.waist?last.waist+' cm':'—'}</strong>${last.waist&&prev.waist?`<small>${last.waist-prev.waist>0?'+':''}${(last.waist-prev.waist).toFixed(1)} cm</small>`:''}</div></div><button class="primary" data-act="checkin">Check-in semanal</button><button class="quietRow" data-act="history"><span>Historial corporal</span><span>${s.checkins.length} check-ins · ${photos} fotos ›</span></button>`)}
function render(){document.querySelector('#app').innerHTML=view==='today'?todayView():progressView();bind()}
function modal(html){document.querySelector('#sheet').innerHTML=html;document.querySelector('#modal').classList.add('show')}
function close(){document.querySelector('#modal').classList.remove('show')}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),900)}
function logExercise(type,amount){amount=Math.max(1,Math.round(n(amount)));day()[type+'Events'].push({id:id(),amount,at:new Date().toISOString()});save();render();toast(`+${amount} ${type==='push'?'flexiones':'dominadas'}`)}
function undoPush(){const a=day().pushEvents;if(a?.length){const e=a.pop();save();render();toast(`−${e.amount} deshecho`)}}
function foodModal(){modal(`<h2>Añadir comida</h2><input class="input" id="foodSearch" placeholder="Buscar comida…" autofocus><div class="searchResults" id="foodResults"></div><button class="secondary" data-act="manual">＋ Crear manualmente</button><p class="note">Los valores de platos preparados son estimaciones editables.</p>`);foodResults('')}
function foodResults(q){const r=foods.filter(f=>f.name.toLowerCase().includes(q.toLowerCase())).slice(0,8);document.querySelector('#foodResults').innerHTML=r.map(f=>`<button data-food="${foods.indexOf(f)}"><b>${f.name}</b><small>${f.kcal} kcal · ${f.p}g proteína</small></button>`).join('');bindSheet()}
function manualForm(pref={}){modal(`<h2>${pref.ai?'Revisar estimación':'Comida manual'}</h2>${pref.image?`<img class="aiPreview" src="${pref.image}">`:''}<form id="mealForm"><input class="input" name="name" placeholder="Comida" value="${esc(pref.name||'')}" required><div class="formgrid"><input class="input" name="kcal" type="number" step="1" placeholder="kcal" value="${pref.kcal??''}" required><input class="input" name="p" type="number" step=".1" placeholder="Proteína g" value="${pref.p??''}"><input class="input" name="c" type="number" step=".1" placeholder="Carbos g" value="${pref.c??''}"><input class="input" name="f" type="number" step=".1" placeholder="Grasa g" value="${pref.f??''}"></div>${pref.ai?'<p class="note">Gemini estima a partir de la imagen. Revisa cantidades, aceite y salsas antes de guardar.</p>':''}<button class="primary">Guardar</button></form>`);document.querySelector('#mealForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);day().meals.push({id:id(),name:f.get('name'),kcal:n(f.get('kcal')),p:n(f.get('p')),c:n(f.get('c')),f:n(f.get('f')),at:new Date().toISOString()});save();close();render()}}
function settings(){modal(`<h2>Ajustes</h2><form id="settingsForm" class="settings"><label>Objetivo flexiones / día</label><input class="input" name="pushGoal" type="number" value="${s.profile.pushGoal}"><label>Objetivo kcal</label><input class="input" name="kcalGoal" type="number" value="${s.profile.kcalGoal}"><label>Proteína / día (g)</label><input class="input" name="proteinGoal" type="number" value="${s.profile.proteinGoal}"><label>Endpoint Gemini</label><input class="input" name="geminiEndpoint" value="${esc(s.profile.geminiEndpoint||'')}" placeholder="Lo configuraremos después"><p class="note">Nunca guardes la API key aquí. La clave irá como secreto en el Worker privado.</p><button class="primary">Guardar</button></form><button class="secondary" data-act="export">Exportar backup</button><button class="secondary" data-act="import">Importar backup</button>`);document.querySelector('#settingsForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);['pushGoal','kcalGoal','proteinGoal'].forEach(k=>s.profile[k]=n(f.get(k)));s.profile.geminiEndpoint=f.get('geminiEndpoint').trim();save();close();render()}}
function checkin(){modal(`<h2>Check-in semanal</h2><p class="note">Medidas y fotos quedan juntas en este check-in. Las fotos no aparecen en la pantalla principal.</p><form id="checkForm"><input class="input" name="weight" type="number" step=".1" placeholder="Peso (kg)"><input class="input" name="waist" type="number" step=".1" placeholder="Cintura (cm)"><details class="optional"><summary>Más medidas (opcional)</summary><input class="input" name="chest" type="number" step=".1" placeholder="Pecho (cm)"><input class="input" name="arm" type="number" step=".1" placeholder="Brazo (cm)"></details><label class="photoPicker">＋ Añadir fotos<input id="checkPhotos" type="file" accept="image/*" multiple hidden></label><div id="photoCount" class="note">0 fotos seleccionadas</div><button class="primary">Guardar check-in</button></form>`);let files=[];document.querySelector('#checkPhotos').onchange=e=>{files=[...e.target.files].slice(0,3);document.querySelector('#photoCount').textContent=`${files.length} foto${files.length===1?'':'s'} seleccionada${files.length===1?'':'s'}`};document.querySelector('#checkForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),photos=[];for(const file of files)photos.push(await compress(file,900,.7));s.checkins.push({id:id(),date:today(),weight:n(f.get('weight'))||null,waist:n(f.get('waist'))||null,chest:n(f.get('chest'))||null,arm:n(f.get('arm'))||null,photos});save();close();render();toast('Check-in guardado')}}
async function compress(file,max=1000,q=.76){const img=await createImageBitmap(file),scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);return c.toDataURL('image/jpeg',q)}
async function analyzeMeal(data){if(!s.profile.geminiEndpoint){manualForm({image:data});return}modal(`<h2>Analizando…</h2><img class="aiPreview" src="${data}"><p class="note">Gemini está estimando alimentos, cantidades y macros.</p>`);try{const r=await fetch(s.profile.geminiEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:data})});if(!r.ok)throw Error();const x=await r.json();manualForm({image:data,ai:true,name:x.name,kcal:x.kcal,p:x.protein_g,c:x.carbs_g,f:x.fat_g})}catch{manualForm({image:data});alert('No se pudo analizar la foto. Puedes introducirla manualmente.')}}
function history(){if(!s.checkins.length){modal(`<h2>Historial corporal</h2><div class="empty">Aún no tienes check-ins.</div>`);return}modal(`<h2>Historial corporal</h2><div class="history">${[...s.checkins].reverse().map(c=>`<button class="historyItem" data-check="${c.id}"><div><b>${new Date(c.date+'T12:00').toLocaleDateString('es',{day:'numeric',month:'short',year:'numeric'})}</b><small>${c.weight?c.weight+' kg · ':''}${c.waist?c.waist+' cm cintura · ':''}${c.photos?.length||0} fotos</small></div><span>›</span></button>`).join('')}</div>${s.checkins.length>1?'<button class="secondary" data-act="compare">Comparar primero ↔ último</button>':''}`);document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>checkDetail(b.dataset.check));bindSheet()}
function checkDetail(cid){const c=s.checkins.find(x=>x.id===cid);if(!c)return;modal(`<button class="back" data-act="history">‹ Historial</button><h2>${new Date(c.date+'T12:00').toLocaleDateString('es',{day:'numeric',month:'long',year:'numeric'})}</h2><div class="bodySummary"><div><span>Peso</span><strong>${c.weight?c.weight+' kg':'—'}</strong></div><div><span>Cintura</span><strong>${c.waist?c.waist+' cm':'—'}</strong></div></div>${c.photos?.length?`<div class="privatePhotos">${c.photos.map(p=>`<img src="${p}">`).join('')}</div>`:'<div class="empty">Sin fotos en este check-in.</div>'}`);bindSheet()}
function compare(){const withPhotos=s.checkins.filter(c=>c.photos?.length);if(withPhotos.length<2){alert('Necesitas al menos dos check-ins con fotos.');return}const a=withPhotos[0],b=withPhotos.at(-1);modal(`<h2>Antes ↔ Ahora</h2><div class="compare"><div class="photo"><img src="${a.photos[0]}"><small>${a.date}</small></div><div class="photo"><img src="${b.photos[0]}"><small>${b.date}</small></div></div><div class="compareStats"><span>${a.weight||'—'} → ${b.weight||'—'} kg</span><span>${a.waist||'—'} → ${b.waist||'—'} cm cintura</span></div><p class="note">Las fotos permanecen guardadas localmente en este dispositivo y en tus backups.</p>`)}
function exportData(){const blob=new Blob([JSON.stringify(s,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`susu-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href)}
function bindSheet(){document.querySelectorAll('[data-food]').forEach(b=>b.onclick=()=>{const f=foods[+b.dataset.food];day().meals.push({...f,id:id(),at:new Date().toISOString()});save();close();render()});document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>action(b.dataset.act));const q=document.querySelector('#foodSearch');if(q)q.oninput=()=>foodResults(q.value)}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});document.querySelectorAll('[data-ex]').forEach(b=>b.onclick=()=>logExercise(b.dataset.ex,n(b.dataset.amount)));document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{period=+b.dataset.period;render()});document.querySelectorAll('[data-metric]').forEach(b=>b.onclick=()=>{metric=b.dataset.metric;render()});document.querySelectorAll('[data-delmeal]').forEach(b=>b.onclick=()=>{day().meals=day().meals.filter(m=>m.id!==b.dataset.delmeal);save();render()});document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>action(b.dataset.act));const m=document.querySelector('#modal');if(m)m.onclick=e=>{if(e.target===m)close()};bindSheet()}
function action(a){if(a==='settings')settings();if(a==='food')foodModal();if(a==='manual')manualForm();if(a==='camera')document.querySelector('#mealCamera').click();if(a==='gallery')document.querySelector('#mealGallery').click();if(a==='customPush'){const x=prompt('¿Cuántas flexiones?');if(n(x)>0)logExercise('push',x)}if(a==='customPull'){const x=prompt('¿Cuántas dominadas?');if(n(x)>0)logExercise('pull',x)}if(a==='undoPush')undoPush();if(a==='checkin')checkin();if(a==='history')history();if(a==='compare')compare();if(a==='export')exportData();if(a==='import')document.querySelector('#importFile').click()}
document.querySelector('#mealCamera').onchange=async e=>{if(e.target.files[0])analyzeMeal(await compress(e.target.files[0],900,.72));e.target.value=''};document.querySelector('#mealGallery').onchange=async e=>{if(e.target.files[0])analyzeMeal(await compress(e.target.files[0],900,.72));e.target.value=''};
document.querySelector('#importFile').onchange=async e=>{try{s={...fresh(),...JSON.parse(await e.target.files[0].text())};save();close();render()}catch{alert('Backup no válido')}e.target.value=''};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
render();
